steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/stable-gig'
      - '-f'
      - 'backend/Dockerfile'
      - 'backend'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'stable-gig'
      - '--image'
      - 'gcr.io/$PROJECT_ID/stable-gig'
      - '--platform'
      - 'managed'
      - '--region'
      - 'europe-west1'
      - '--allow-unauthenticated'
      - '--execution-environment'
      - 'gen2'
      - '--memory'
      - '2Gi'
      - '--timeout'
      - '900'
      - '--set-env-vars'
      - 'SUPABASE_URL=https://szpgcvfemllcsajryyuv.supabase.co'
      - '--set-secrets'
      - 'GEMINI_API_KEY=GEMINI_API_KEY:latest,SUPABASE_ANON_KEY=SUPABASE_ANON_KEY:latest,SUPABASE_SERVICE_KEY=SUPABASE_SERVICE_KEY:latest'
images:
  - 'gcr.io/$PROJECT_ID/stable-gig'
